const mutations = {
  SET_SETTINGS: 'SET_SETTINGS',
  SET_HAS_APP: 'SET_HAS_APP',
  SET_EXTENSION_VERSION: 'SET_EXTENSION_VERSION',

  IS_GOOGLE_CHROME: 'IS_GOOGLE_CHROME',
  IS_MOBILE_CHANGE: 'IS_MOBILE_CHANGE',
}

export { mutations }
